<?php

/**
 * Implements hook_theme().
 */
function culturefeed_udb3_app_theme() {
  return array(
    'udb3_search' => array(
      'variables' => array(),
    ),
    'udb3_anonymous_landing' => array(
      'variables' => array(),
    ),
    'udb3_dashboard' => array(
      'variables' => array(
        'username' => '',
      ),
    ),
    'udb3_event_form' => array(
      'variables' => array(
        'item_id' => NULL,
      ),
    )
  );
}

/**
 * Implements hook_page_attachments().
 */
function culturefeed_udb3_app_page_attachments(array &$page) {
  $udb3AppSettings = Drupal::config('culturefeed_udb3_app.settings');

  /** @var \Drupal\Core\Routing\UrlGeneratorInterface $urlGenerator */
  $urlGenerator = Drupal::service('url_generator');

  /** @var \Drupal\Core\Utility\UnroutedUrlAssemblerInterface $unroutedUrlAssembler */
  $unroutedUrlAssembler = Drupal::service('unrouted_url_assembler');

  $apiPath = $unroutedUrlAssembler->assemble(
    'base://udb3/api/1.0/',
    array('absolute' => TRUE)
  );
  $udb3BasePath = $unroutedUrlAssembler->assemble(
    'base://' . drupal_get_path('module', 'culturefeed_udb3_app') . '/bower_components/udb3-angular',
    array('absolute' => TRUE)
  );
  global $base_url;

  $page['#attached']['drupalSettings']['culturefeed_udb3_app']['appConfig'] = [
    'baseUrl' => $apiPath,
    'baseApiUrl' => $apiPath,
    'udb3JsBaseUrl' => $udb3BasePath,
    'udb3BaseUrl' => $base_url,
    'authUrl' => $urlGenerator->generateFromRoute(
      'culturefeed.oauth.connect',
      array(),
      array('absolute' => TRUE)
    ),
    'socketUrl' => $udb3AppSettings->get('websocket_server')
  ];
}
